# Generated by Django 5.0.3 on 2024-03-22 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='KindProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=25, verbose_name='Название вида продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, verbose_name='Описание продукда')),
                ('kind_product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.kindproduct', verbose_name='Вид продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['kind_product', 'name'],
                'unique_together': {('name', 'kind_product')},
            },
        ),
    ]
