# Generated by Django 5.0.3 on 2024-03-22 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindproduct',
            options={'verbose_name': 'Вид продукта', 'verbose_name_plural': 'Виды продуктов'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterModelTable(
            name='kindproduct',
            table='kind_products',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название')),
                ('date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.product')),
            ],
            options={
                'verbose_name': 'Продукт клиента',
                'verbose_name_plural': 'Продукты клиентов',
            },
        ),
    ]
