# Generated by Django 5.0.3 on 2024-03-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_kindproduct_options_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproduct',
            name='name',
        ),
    ]
