# Generated by Django 5.0.3 on 2024-03-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_clientproduct_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindproduct',
            options={'ordering': ['name'], 'verbose_name': 'Вид продукта', 'verbose_name_plural': 'Виды продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(default='2099-12-31', verbose_name='Срок действия'),
        ),
        migrations.AlterUniqueTogether(
            name='kindproduct',
            unique_together={('name',)},
        ),
    ]
