# Generated by Django 5.0.3 on 2024-03-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_kindproduct_options_product_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(default='2099-12-31', verbose_name='Срок действия'),
        ),
    ]
