# Generated by Django 5.0.3 on 2024-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_product_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, default='2050.11.31', null=True, verbose_name='Срок действия'),
        ),
    ]
