# Generated by Django 5.0.3 on 2024-03-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_product_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_date',
        ),
    ]
