# Generated by Django 5.0.3 on 2024-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_remove_product_end_date_remove_product_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, default='2099-11-30', null=True, verbose_name='Срок действия'),
        ),
    ]
