# Generated by Django 5.0.3 on 2024-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_product_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, default='2099-12-31', null=True, verbose_name='Срок действия'),
        ),
    ]
