# Generated by Django 5.0.3 on 2024-03-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_client_address_client_phone_alter_client_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
