# Generated by Django 5.0.3 on 2024-03-17 10:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_course_alter_client_options_client_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='course',
            field=models.ManyToManyField(blank=True, to='shop.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_num',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('java', 'Java')], default=None, max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'course_num')},
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.course')),
            ],
        ),
    ]
