# Generated by Django 5.0.3 on 2024-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_kindproduct_modelscategory_remove_grade_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='course',
            new_name='kind_product',
        ),
        migrations.RenameField(
            model_name='kindproduct',
            old_name='name',
            new_name='kind',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
