# Generated by Django 5.0.3 on 2024-03-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_kind_clientproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindproduct',
            options={'ordering': ['product', 'kind'], 'verbose_name': 'Вид продукта', 'verbose_name_plural': 'Виды продуктов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='clients_first_n_7c0dc6_idx',
        ),
    ]
